
development:
  host: localhost
  adapter: postgis
  encoding: unicode
  database: bogo
  pool: 5
  username: postgres
  password: <%= ENV['PSQL_PASSWD'] %>

test:
  adapter: postgis
  database: bogo_test
  pool: 5
  username: postgres

production:
  database: bogo_prod
  adapter: postgis
  encoding: unicode
  username: spalatin
  pool: 5
  password: